version: "3.8"

services:
  buku-ibu-db:
    container_name: buku_ibu_db
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'buku_ibu_mysql'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      DATABASE_HOST: 'buku_ibu_db'
    volumes:
      - type: volume
        source: database-mysql
        target: /var/lib/mysql
    networks:
      - buku-ibu-networks
  buku-ibu-app:
    container_name: buku-ibu-app
    build: .
    volumes:
      - type: volume
        source: api
        target: /usr/src/app
    restart: on-failure
    ports:
      - 8080:8080
#    command: [ "./wait-for", "buku_ibu_db:3306", "--", "--", "./main" ]
    networks:
      - buku-ibu-networks
    depends_on:
      - buku-ibu-db

networks:
  buku-ibu-networks:
    driver: bridge

volumes:
  api:
  database-mysql: