version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_USER=${db_user}
      - POSTGRES_DB=${db_name}
      - DATABASE_HOST=${db_host}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - buku-ibu-networks
  buku-ibu-app:
    container_name: buku-ibu-app
    image: api-buku-ibu:1.0
    ports:
      - 8080:80
    networks:
      - buku-ibu-networks
    depends_on:
      - postgres

networks:
  buku-ibu-networks:

volumes:
  api:
  postgres-data: